### ISSUE TITLE
Production deployments need to be set up

### ISSUE THREAD

**Issue by alex-demetriou** [LBHackney-IT/repairs-api-dotnet#75]
### Do not perform first release until:
- [x] Manual Approval stage for production release enabled
- [x] Parameters added to SSM #73 
- [x] Added Terraform for Production

### Other steps
- [x] Add Security Group to `serverless.yml` for Production
- [ ] Set up canaries for healthcheck etc. #71 
- [x] Enable API Gateway Logging #72 
- [x] Add Consumer Tokens for Repairs #76 
- [ ] Set up Lambda Authorizer to replace `X-Api-Key` auth #70
